spring:
  application:
    name: api-gateway
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    
server:
  port: 8080
  
zuul:
  host:
    socket-timeout-millis: 60000
    connect-timout-millis: 60000
  ratelimit:
    enabled: true
    repository: JPA
    behind-proxy: true
    default-policy-list: # limite 10 request in 30 seconds
    - limit: 10 
      refresh-interval: 30 

ribbon:
  eureka:
    enabled: true  #important
  ReadTimeout: 60000
  ConnectTimeout: 60000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 240000 #important
      
management:
  endpoints:
    web:
      exposure:
        include: routes,filters

okta:
  oauth2:
    issuer: https://dev-8366513.okta.com/oauth2/default

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}