spring:
  application:
    name: product-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
server:
  port: 8082
  
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}

# Redis Config
spring.redis.host: localhost
spring.redis.port: 6379

#Message queue name
product-service.search-queue: product-search-queue